### ISSUE TITLE
It doesn't work on mobile

### ISSUE THREAD

**Issue by idk-idk-idkfhdhfhfh** [TheTerrarian101/MindustryMod-Insanely-OverPowered-EX-Mod#2]
I believe if you move the mod.json file out to the front it might fix it,though I'm unsure

**Comment by Founderroni** [comment]
> I believe if you move the mod.json file out to the front it might fix it,though I'm unsure

It should work on mobile as that is what I test it on, instead of pressing the download source button, press the mod .zip file and press download on the top right. If this doesn't work or if u already did this try installing. If you run into a bug where it crashes it happens just extract the file, edit the mod.json file, compress into zip, rename zip file (cannot be same name as original download). If any more bugs occur please say what exactly happened and I'll see if I can fix it.
